### ISSUE TITLE
Template for tracking tests

### ISSUE THREAD

**Issue by bermud** [opengeospatial/cite#12]
# Status of test suites

- [ ] An issue is created for the test in [CITE tracker] (https://github.com/opengeospatial/cite/issues).
- [ ] Project is in github
- [ ] Test is released in beta
- [ ] Reference Implementations are confirmed
   - [ ] Ref 1
   - [ ] ..
- [ ] Checked status and follow up with test suite and reference implementation developers (every two weeks)
   - Last checked (*date*)
   - Due date (*date* )
- [ ] Test is ready (RI are OK) - send to CITE SC review (one week)
- [ ] Sent to TC Chair for TC Vote ( 1-2 months)
- [ ] Sent to  OAB (wait one week)
- [ ] Test is moved to production
- [ ] World is notified
